name: CC

on:
  push:
    branches: [ nightly, stable ]
  pull_request:
    branches: [ nightly, stable ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rustup nightly
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
